import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import { Toaster } from "@/components/ui/toaster";
import StoreProvider from "@/store/StoreProvider";
import getThemeCookie from "@/utils/getThemeCookie.mjs";
import { verifyToken } from "@/utils/verifyToken.mjs";
import { makeStore } from "@/store/store";
import { setUserData } from "@/store/slices/authSlice";
import { setTheme } from "@/store/slices/themeSlice";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Invest Management",
  description: "Generated by Hasn",
};

export default async function RootLayout({ children }) {
  let storedTheme = await getThemeCookie();
  let userData = await verifyToken();
  const store = makeStore();
  store.dispatch(setUserData(userData));
  store.dispatch(setTheme(storedTheme));
  const initialReduxState = store.getState();
  return (
    <StoreProvider initialReduxState={initialReduxState}>
      <html lang="en" data-theme={storedTheme}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar />
          {children}
          <Toaster />
        </body>
      </html>
    </StoreProvider>
  );
}
